/// AI Response Models
/// These models define the structure of AI-generated content
/// for the Study Assistant feature.
library;

/// Represents a summary generated by the AI
class AISummary {
  final List<String> keyPoints;
  final String fullSummary;
  final DateTime timestamp;
  final String sourceContext;

  AISummary({
    required this.keyPoints,
    required this.fullSummary,
    required this.timestamp,
    required this.sourceContext,
  });

  Map<String, dynamic> toJson() => {
    'keyPoints': keyPoints,
    'fullSummary': fullSummary,
    'timestamp': timestamp.toIso8601String(),
    'sourceContext': sourceContext,
  };

  factory AISummary.fromJson(Map<String, dynamic> json) => AISummary(
    keyPoints: List<String>.from(json['keyPoints']),
    fullSummary: json['fullSummary'],
    timestamp: DateTime.parse(json['timestamp']),
    sourceContext: json['sourceContext'],
  );
}

/// Represents an answer to a student's question
class AIAnswer {
  final String question;
  final String answer;
  final String? sourceReference;
  final DateTime timestamp;
  final bool isRelevant;

  AIAnswer({
    required this.question,
    required this.answer,
    this.sourceReference,
    required this.timestamp,
    this.isRelevant = true,
  });

  Map<String, dynamic> toJson() => {
    'question': question,
    'answer': answer,
    'sourceReference': sourceReference,
    'timestamp': timestamp.toIso8601String(),
    'isRelevant': isRelevant,
  };

  factory AIAnswer.fromJson(Map<String, dynamic> json) => AIAnswer(
    question: json['question'],
    answer: json['answer'],
    sourceReference: json['sourceReference'],
    timestamp: DateTime.parse(json['timestamp']),
    isRelevant: json['isRelevant'] ?? true,
  );
}

/// Represents a quiz question generated by the AI
class AIQuizItem {
  final String question;
  final List<String> options;
  final int correctAnswerIndex;
  final String explanation;
  final String topic;
  final QuizDifficulty difficulty;
  final DateTime timestamp;

  AIQuizItem({
    required this.question,
    required this.options,
    required this.correctAnswerIndex,
    required this.explanation,
    required this.topic,
    required this.difficulty,
    required this.timestamp,
  });

  Map<String, dynamic> toJson() => {
    'question': question,
    'options': options,
    'correctAnswerIndex': correctAnswerIndex,
    'explanation': explanation,
    'topic': topic,
    'difficulty': difficulty.toString().split('.').last,
    'timestamp': timestamp.toIso8601String(),
  };

  factory AIQuizItem.fromJson(Map<String, dynamic> json) => AIQuizItem(
    question: json['question'],
    options: List<String>.from(json['options']),
    correctAnswerIndex: json['correctAnswerIndex'],
    explanation: json['explanation'],
    topic: json['topic'],
    difficulty: QuizDifficulty.values.firstWhere(
      (e) => e.toString().split('.').last == json['difficulty'],
      orElse: () => QuizDifficulty.medium,
    ),
    timestamp: DateTime.parse(json['timestamp']),
  );
}

/// Quiz difficulty levels
enum QuizDifficulty {
  easy,
  medium,
  hard,
  expert,
}

/// Represents the status of an AI operation
class AIOperationStatus {
  final bool isLoading;
  final String? error;
  final bool isSuccess;

  AIOperationStatus({
    this.isLoading = false,
    this.error,
    this.isSuccess = false,
  });

  AIOperationStatus copyWith({
    bool? isLoading,
    String? error,
    bool? isSuccess,
  }) {
    return AIOperationStatus(
      isLoading: isLoading ?? this.isLoading,
      error: error,
      isSuccess: isSuccess ?? this.isSuccess,
    );
  }
}

